### ISSUE TITLE
On Raspberry Pi, an unhandled exception is happening every second or so

### ISSUE THREAD

**Issue by devbotas** [tevux-tech/bhd#24]
3blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'mudHandlePortal' ('mudHandlePortal' was undefined).
      Error: Could not find 'mudHandlePortal' ('mudHandlePortal' was undefined).
          at http://172.16.0.136/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (http://172.16.0.136/_framework/blazor.webassembly.js:1:1247)
          at b (http://172.16.0.136/_framework/blazor.webassembly.js:1:2989)
          at http://172.16.0.136/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (http://172.16.0.136/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (http://172.16.0.136/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (http://172.16.0.136/_framework/dotnet.5.0.9.js:1:190800)
          at do_icall (http://172.16.0.136/_framework/dotnet.wasm:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'mudHandlePortal' ('mudHandlePortal' was undefined).
Error: Could not find 'mudHandlePortal' ('mudHandlePortal' was undefined).
    at http://172.16.0.136/_framework/blazor.webassembly.js:1:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (http://172.16.0.136/_framework/blazor.webassembly.js:1:1247)
    at b (http://172.16.0.136/_framework/blazor.webassembly.js:1:2989)
    at http://172.16.0.136/_framework/blazor.webassembly.js:1:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (http://172.16.0.136/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (http://172.16.0.136/_framework/blazor.webassembly.js:1:64232)
    at _mono_wasm_invoke_js_blazor (http://172.16.0.136/_framework/dotnet.5.0.9.js:1:190800)
    at do_icall (http://172.16.0.136/_framework/dotnet.wasm:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at MudBlazor.MudPortal.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.9.js:1
do_icall @ dotnet.wasm:0x194e4e
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_try_invoke @ dotnet.wasm:0x12982
mono_runtime_invoke @ dotnet.wasm:0x10ec2b
mono_wasm_invoke_method @ dotnet.wasm:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.9.js:1
call_method @ dotnet.5.0.9.js:1
(anonymous) @ dotnet.5.0.9.js:1
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.9.js:1
do_icall @ dotnet.wasm:0x194e4e
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_try_invoke @ dotnet.wasm:0x12982
mono_runtime_invoke @ dotnet.wasm:0x10ec2b
mono_wasm_invoke_method @ dotnet.wasm:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.9.js:1
call_method @ dotnet.5.0.9.js:1
set_task_result @ dotnet.5.0.9.js:1
(anonymous) @ dotnet.5.0.9.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.9.js:1
mono_wasm_convert_return_value @ dotnet.5.0.9.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.9.js:1
do_icall @ dotnet.wasm:0x194ddb
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_try_invoke @ dotnet.wasm:0x12982
mono_runtime_invoke @ dotnet.wasm:0x10ec2b
mono_wasm_invoke_method @ dotnet.wasm:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.9.js:1
call_method @ dotnet.5.0.9.js:1
set_task_result @ dotnet.5.0.9.js:1
(anonymous) @ dotnet.5.0.9.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.9.js:1
mono_wasm_convert_return_value @ dotnet.5.0.9.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.9.js:1
do_icall @ dotnet.wasm:0x194ddb
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_try_invoke @ dotnet.wasm:0x12982
tp_cb @ dotnet.wasm:0xf7d88
mono_background_exec @ dotnet.wasm:0x9a696
Module._mono_background_exec @ dotnet.5.0.9.js:1
pump_message @ dotnet.5.0.9.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.5.0.9.js:1
mono_threads_schedule_background_job @ dotnet.wasm:0x26ea8
mono_wasm_queue_tp_cb @ dotnet.wasm:0x108c2f
do_icall @ dotnet.wasm:0x194eeb
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_invoke_checked @ dotnet.wasm:0xf65d
mono_runtime_try_invoke_array @ dotnet.wasm:0x10e831
ves_icall_InternalInvoke @ dotnet.wasm:0xed492
ves_icall_InternalInvoke_raw @ dotnet.wasm:0xecf57
do_icall @ dotnet.wasm:0x194ddb
do_icall_wrapper @ dotnet.wasm:0x79df9
interp_exec_method @ dotnet.wasm:0x44ad3
interp_runtime_invoke @ dotnet.wasm:0x12efff
mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
do_runtime_invoke @ dotnet.wasm:0x79d42
mono_runtime_try_invoke @ dotnet.wasm:0x12982
mono_runtime_invoke @ dotnet.wasm:0x10ec2b
mono_wasm_invoke_method @ dotnet.wasm:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.9.js:1
call_method @ dotnet.5.0.9.js:1
invoke_delegate @ dotnet.5.0.9.js:1
(anonymous) @ dotnet.5.0.9.js:1

**Comment by Girdauskas** [comment]
Will solve in #27
